/*
 * ID LINK
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package idlink.ig.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LoginApi
 */
@Ignore
public class LoginApiTest {

    private final LoginApi api = new LoginApi();

    /**
     * oauth2 authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2AuthorizeTest() throws ApiException {
        String clientId = null;
        String redirectUri = null;
        String responseType = null;
        String state = null;
        String response = api.oAuth2Authorize(clientId, redirectUri, responseType, state);

        // TODO: test validations
    }
    /**
     * oauth2 authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2Authorize1Test() throws ApiException {
        String clientId = null;
        String redirectUri = null;
        String responseType = null;
        String state = null;
        String response = api.oAuth2Authorize1(clientId, redirectUri, responseType, state);

        // TODO: test validations
    }
    /**
     * oauth2 authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2Authorize2Test() throws ApiException {
        String clientId = null;
        String redirectUri = null;
        String responseType = null;
        String state = null;
        String response = api.oAuth2Authorize2(clientId, redirectUri, responseType, state);

        // TODO: test validations
    }
    /**
     * oauth2 authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2Authorize3Test() throws ApiException {
        String clientId = null;
        String redirectUri = null;
        String responseType = null;
        String state = null;
        String response = api.oAuth2Authorize3(clientId, redirectUri, responseType, state);

        // TODO: test validations
    }
    /**
     * oauth2 authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2Authorize4Test() throws ApiException {
        String clientId = null;
        String redirectUri = null;
        String responseType = null;
        String state = null;
        String response = api.oAuth2Authorize4(clientId, redirectUri, responseType, state);

        // TODO: test validations
    }
    /**
     * oauth2 authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2Authorize5Test() throws ApiException {
        String clientId = null;
        String redirectUri = null;
        String responseType = null;
        String state = null;
        String response = api.oAuth2Authorize5(clientId, redirectUri, responseType, state);

        // TODO: test validations
    }
    /**
     * oauth2 authorize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2Authorize6Test() throws ApiException {
        String clientId = null;
        String redirectUri = null;
        String responseType = null;
        String state = null;
        String response = api.oAuth2Authorize6(clientId, redirectUri, responseType, state);

        // TODO: test validations
    }
    /**
     * oauth2 login
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuth2LoginTest() throws ApiException {
        String password = null;
        String reqcode = null;
        String userName = null;
        api.oAuth2Login(password, reqcode, userName);

        // TODO: test validations
    }
}
