/*
 * ID LINK
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package idlink.ig.client.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * AdminExchangeAccessTokenRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-14T18:48:52.841+08:00[Asia/Shanghai]")
public class AdminExchangeAccessTokenRequest {
  @SerializedName("accessToken")
  private String accessToken = null;

  @SerializedName("clientMetadata")
  private Map<String, Object> clientMetadata = null;

  public AdminExchangeAccessTokenRequest accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * User&#x27; accessToken
   * @return accessToken
  **/
  @Schema(example = "jwt protocol", required = true, description = "User' accessToken")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public AdminExchangeAccessTokenRequest clientMetadata(Map<String, Object> clientMetadata) {
    this.clientMetadata = clientMetadata;
    return this;
  }

  public AdminExchangeAccessTokenRequest putClientMetadataItem(String key, Object clientMetadataItem) {
    if (this.clientMetadata == null) {
      this.clientMetadata = new HashMap<String, Object>();
    }
    this.clientMetadata.put(key, clientMetadataItem);
    return this;
  }

   /**
   * Client meta data
   * @return clientMetadata
  **/
  @Schema(example = "{\"param1\":\"value1\",\"param2\":\"value2\"}", description = "Client meta data")
  public Map<String, Object> getClientMetadata() {
    return clientMetadata;
  }

  public void setClientMetadata(Map<String, Object> clientMetadata) {
    this.clientMetadata = clientMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    AdminExchangeAccessTokenRequest adminExchangeAccessTokenRequest = (AdminExchangeAccessTokenRequest) o;
    return ObjectUtils.equals(this.accessToken, adminExchangeAccessTokenRequest.accessToken) &&
    ObjectUtils.equals(this.clientMetadata, adminExchangeAccessTokenRequest.clientMetadata);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(accessToken, clientMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminExchangeAccessTokenRequest {\n");
    
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    clientMetadata: ").append(toIndentedString(clientMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
