/*
 * ID LINK
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package idlink.ig.client.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * AdminExchangeAccessTokenRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-20T14:36:13.595+08:00[Asia/Shanghai]")
public class AdminExchangeAccessTokenRequest {
  @SerializedName("accessToken")
  private String accessToken = null;

  @SerializedName("dynamicClaim")
  private Map<String, Object> dynamicClaim = null;

  public AdminExchangeAccessTokenRequest accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * User&#x27; accessToken
   * @return accessToken
  **/
  @Schema(example = "jwt protocol", required = true, description = "User' accessToken")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public AdminExchangeAccessTokenRequest dynamicClaim(Map<String, Object> dynamicClaim) {
    this.dynamicClaim = dynamicClaim;
    return this;
  }

  public AdminExchangeAccessTokenRequest putDynamicClaimItem(String key, Object dynamicClaimItem) {
    if (this.dynamicClaim == null) {
      this.dynamicClaim = new HashMap<String, Object>();
    }
    this.dynamicClaim.put(key, dynamicClaimItem);
    return this;
  }

   /**
   * Client meta data
   * @return dynamicClaim
  **/
  @Schema(example = "{\"param1\":\"value1\",\"param2\":\"value2\"}", description = "Client meta data")
  public Map<String, Object> getDynamicClaim() {
    return dynamicClaim;
  }

  public void setDynamicClaim(Map<String, Object> dynamicClaim) {
    this.dynamicClaim = dynamicClaim;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    AdminExchangeAccessTokenRequest adminExchangeAccessTokenRequest = (AdminExchangeAccessTokenRequest) o;
    return ObjectUtils.equals(this.accessToken, adminExchangeAccessTokenRequest.accessToken) &&
    ObjectUtils.equals(this.dynamicClaim, adminExchangeAccessTokenRequest.dynamicClaim);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(accessToken, dynamicClaim);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminExchangeAccessTokenRequest {\n");
    
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    dynamicClaim: ").append(toIndentedString(dynamicClaim)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
